/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pe.edu.cientifica.view;
import java.util.List;
import java.util.Map;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pe.edu.cientifica.model.Alumno;
import pe.edu.cientifica.model.Carrera;
import pe.edu.cientifica.model.Detalle;
import pe.edu.cientifica.daoImp.AlumnoDaoImp;
import pe.edu.cientifica.daoImp.CarreraDaoImp;
import pe.edu.cientifica.daoImp.DetalleDaoImp;

/**
 *
 * @author José
 */
public class MatriculaForm extends javax.swing.JFrame {
 private AlumnoDaoImp dao = new AlumnoDaoImp();
 private CarreraDaoImp cdi = new CarreraDaoImp();
 private DetalleDaoImp ddi = new DetalleDaoImp();
 private DefaultTableModel model;
 private DefaultComboBoxModel modelCombo;
 private int fila=-1;
 int idcar =0;
 int idalu=0;
 int iddeta=0;
    /**
     * Creates new form MatriculaForm
     */
    public MatriculaForm() {
        initComponents();
        setLocationRelativeTo(null);       
        cargarCombo();
        listarRegistro();
        inicio();
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnguardar = new javax.swing.JButton();
        btnactualizar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        txtciclo = new javax.swing.JTextField();
        txtmodalidad = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        txtfechainicio = new javax.swing.JTextField();
        txtapellido = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtfechafin = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtprecio = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtdistrito = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtdni = new javax.swing.JTextField();
        cboCarrera = new javax.swing.JComboBox<>();
        txtidcarrera = new javax.swing.JTextField();
        btnnuevo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbdatos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registro de matricula 2023-1", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        jLabel5.setText("Nombre:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        jLabel6.setText("Ciclo:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        jLabel7.setText("Modalidad:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        jLabel8.setText("Fecha Inicio:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        jLabel10.setText("Carrera:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 50, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        jLabel11.setText("Apellido:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, -1, -1));

        btnguardar.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        btnguardar.setText("REGISTRAR");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, -1, -1));

        btnactualizar.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        btnactualizar.setText("MODIFICAR");
        btnactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualizarActionPerformed(evt);
            }
        });
        jPanel1.add(btnactualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, -1, -1));

        btneliminar.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        btneliminar.setText("ELIMINAR");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btneliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, -1, -1));
        jPanel1.add(txtciclo, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, 130, -1));
        jPanel1.add(txtmodalidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, 130, -1));
        jPanel1.add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 120, -1));
        jPanel1.add(txtfechainicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 119, -1));

        txtapellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtapellidoActionPerformed(evt);
            }
        });
        jPanel1.add(txtapellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, 130, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        jLabel3.setText("Fecha Fin:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));
        jPanel1.add(txtfechafin, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 120, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        jLabel4.setText("Precio:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 100, -1, -1));
        jPanel1.add(txtprecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 100, 150, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        jLabel9.setText("Distrito:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 150, -1, -1));
        jPanel1.add(txtdistrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 150, 150, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        jLabel12.setText("DNI:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));
        jPanel1.add(txtdni, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 120, -1));

        cboCarrera.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboCarreraItemStateChanged(evt);
            }
        });
        cboCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboCarreraActionPerformed(evt);
            }
        });
        jPanel1.add(cboCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 60, 150, -1));

        txtidcarrera.setEditable(false);
        txtidcarrera.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtidcarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(834, 60, 80, -1));

        btnnuevo.setText("Nuevo");
        btnnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevoActionPerformed(evt);
            }
        });
        jPanel1.add(btnnuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 240, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel2.setText("MATRICULA 2023-1");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Listado de matricula", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        tbdatos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tbdatos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tbdatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "IDALUMNO", "Nombre", "Apellido", "Ciclo", "Distrito", "DNI", "IDCARRERA", "Carrera", "IDDETALLE", "Precio", "Fecha Inicio", "Fecha Fin", "Modalidad"
            }
        ));
        tbdatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbdatosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbdatos);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 895, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 947, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 15, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 926, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap())
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 854, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(0, 0, Short.MAX_VALUE)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addGap(0, 0, 0)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        if(idcar>0){
            dao.create(new Alumno(idalu, txtnombre.getText(), txtapellido.getText(), txtciclo.getText(),
                    txtdistrito.getText(), txtdni.getText(), idcar));
            ddi.create(new Detalle(iddeta, txtprecio.getText(), txtfechainicio.getText(),
                    txtfechafin.getText(), txtmodalidad.getText(), idcar));
                    JOptionPane.showMessageDialog(rootPane, "Producto Guardado Correctamente...!");
                    limpiarFormulario();
                    limpiar_table();
                    listarRegistro();
        }else{
            JOptionPane.showMessageDialog(rootPane, "Seleccionar Categoría");
        
        }
    }//GEN-LAST:event_btnguardarActionPerformed

    private void btnactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizarActionPerformed
        if(fila>=0){
            int result = JOptionPane.showConfirmDialog(this,"Realmente desea modificar el Registro?", "Swing Tester",
               JOptionPane.YES_NO_OPTION,
               JOptionPane.QUESTION_MESSAGE);
            switch (result) {
                case JOptionPane.YES_OPTION:
                    dao.update(new Alumno(idalu, txtnombre.getText(), txtapellido.getText(), 
                            txtciclo.getText(), txtdistrito.getText(), txtdni.getText(), idcar));
                    ddi.update(new Detalle(iddeta,txtprecio.getText(), txtfechainicio.getText(), 
                            txtfechafin.getText(), txtmodalidad.getText(), idcar));
                    limpiar_table();
                    listarRegistro();
                    cargarCombo();
                    limpiarFormulario();
                    JOptionPane.showMessageDialog(rootPane, "Se ha Actualizado Correctamente...!");
                    break;
                case JOptionPane.NO_OPTION:
                    JOptionPane.showMessageDialog(rootPane, "No se ha Actualizado la Categoría");
                    break;
                default:
                    break;
            }
        }else{
            JOptionPane.showMessageDialog(rootPane, "Seleccionar Producto");
        }
    }//GEN-LAST:event_btnactualizarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        if(fila>=0){
            int result = JOptionPane.showConfirmDialog(this,"Realmente desea eliminar la Producto?", "Swing Tester",
               JOptionPane.YES_NO_OPTION,
               JOptionPane.QUESTION_MESSAGE);
            switch (result) {
                case JOptionPane.YES_OPTION:
                    dao.delete(idalu);
                    ddi.delete(iddeta);
                    limpiar_table();
                    listarRegistro();
                    limpiarFormulario();
                    cargarCombo();
                    JOptionPane.showMessageDialog(rootPane, "Se ha eliminado Correctamente...!");
                    break;
                case JOptionPane.NO_OPTION:
                    JOptionPane.showMessageDialog(rootPane, "No se ha Eliminado la Producto");
                    break;
                default:
                    break;
            }
        }else{
            JOptionPane.showMessageDialog(rootPane, "Seleccionar Producto");
        }
    }//GEN-LAST:event_btneliminarActionPerformed

    private void tbdatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbdatosMouseClicked
        btnguardar.setEnabled(false);
        btneliminar.setEnabled(true);
        btnactualizar.setEnabled(true);
        modelCombo = new DefaultComboBoxModel();
        cboCarrera.setModel(modelCombo);
        fila = tbdatos.getSelectedRow();
        Carrera car = cdi.read(Integer.parseInt(tbdatos.getValueAt(fila, 7).toString()));
        idalu = Integer.parseInt(tbdatos.getValueAt(fila, 1).toString());
        iddeta=Integer.parseInt(tbdatos.getValueAt(fila,9).toString());
        cargarCombo();
        modelCombo.setSelectedItem(car);
        txtnombre.setText(tbdatos.getValueAt(fila, 2).toString());
        txtapellido.setText(tbdatos.getValueAt(fila, 3).toString());
        txtciclo.setText(tbdatos.getValueAt(fila, 4).toString());
        txtdistrito.setText(tbdatos.getValueAt(fila, 5).toString());
        txtdni.setText(tbdatos.getValueAt(fila, 6).toString());
        txtprecio.setText(tbdatos.getValueAt(fila, 10).toString());
        txtfechainicio.setText(tbdatos.getValueAt(fila, 11).toString());
        txtfechafin.setText(tbdatos.getValueAt(fila, 12).toString());
        txtmodalidad.setText(tbdatos.getValueAt(fila, 13).toString());
    }//GEN-LAST:event_tbdatosMouseClicked

    private void cboCarreraItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboCarreraItemStateChanged
        // TODO add your handling code here:
        Carrera car = (Carrera) cboCarrera.getSelectedItem();
        idcar = car.getIdcarrera();
        txtidcarrera.setText(""+idcar);

    }//GEN-LAST:event_cboCarreraItemStateChanged

    private void txtapellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtapellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtapellidoActionPerformed

    private void cboCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboCarreraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboCarreraActionPerformed

    private void btnnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevoActionPerformed
        btnguardar.setEnabled(true);
        btneliminar.setEnabled(false);
        btnactualizar.setEnabled(false);
        limpiarFormulario();
        limpiar_table();
        listarRegistro();
    }//GEN-LAST:event_btnnuevoActionPerformed

    private void inicio(){
        btnguardar.setEnabled(false);
        btneliminar.setEnabled(false);
        btnactualizar.setEnabled(false);
    }    
    private void cargarCombo(){
        modelCombo = new DefaultComboBoxModel();
        cboCarrera.setModel(modelCombo);
        List<Carrera> lista1 = cdi.readAll();
        Carrera cat  = new Carrera();
        cboCarrera.removeAllItems();
        modelCombo.addElement(new Carrera(0,"Seleccionar Categoría",0));
        for(int i=0;i<lista1.size();i++){
            modelCombo.addElement(new Carrera(lista1.get(i).getIdcarrera(),lista1.get(i).getNombre(),lista1.get(i).getEstado()));
        }
    }
    /*private void listarRegistro(){
        model = (DefaultTableModel)tbdatos.getModel();
        List<Map<String, Object>> lista2 = dao.readAll2();
        List<Map<String, Object>> lista3 = ddi.readAll2();
        Object[] datos = new Object[14];
        int x = 1;
        for (Map row : lista2) {
              datos[0]=x;
              datos[1]=row.get("idalumno");
              datos[2]=row.get("alumno");
              datos[3]=row.get("apellido");
              datos[4]=row.get("ciclo");
              datos[5]=row.get("distrito");
              datos[6]=row.get("dni");
              datos[7]=row.get("idcarrera");
              datos[8]=row.get("carrera");
              datos[9]=row.get("iddetalle");
              datos[10]=row.get("precio");
              datos[11]=row.get("fechainicio");
              datos[12]=row.get("fechafinal");
              datos[13]=row.get("modalidad");
              model.addRow(datos); 
              x++;
        }
        tbdatos.setModel(model);
    
    }*/
    private void limpiar_table(){
        for(int i=0; i<tbdatos.getRowCount();i++){
            model.removeRow(i);
            i=-1;
        }    
    }
    private void limpiarFormulario(){
        cboCarrera.setSelectedIndex(0);
        txtnombre.setText("");
        txtapellido.setText("");
        txtciclo.setText("");
        txtfechainicio.setText("");
        txtfechafin.setText("");
        txtmodalidad.setText("");
        txtprecio.setText("");
        txtdni.setText("");
        txtdistrito.setText("");
        idcar=0;
        idalu=0;
        iddeta=0;
    }
    private void listarRegistro(){
        limpiar_table();
        model = (DefaultTableModel)tbdatos.getModel();
        List<Map<String, Object>> lista = dao.readAll2();
        List<Map<String, Object>> lista2 = ddi.readAll2();
        Object datos[] =new Object[14];
        int x=1;
        for(int i=0;i<lista.size();i++){
            datos[0]=x;
            datos[1]=lista.get(i).get("idalumno");
            datos[2]=lista.get(i).get("alumno");
            datos[3]=lista.get(i).get("apellido");
            datos[4]=lista.get(i).get("ciclo");
            datos[5]=lista.get(i).get("distrito");
            datos[6]=lista.get(i).get("dni");
            datos[7]=lista.get(i).get("idcarrera");
            datos[8]=lista.get(i).get("carrera");
            datos[9]=lista2.get(i).get("iddetalle");
            datos[10]=lista2.get(i).get("precio");
            datos[11]=lista2.get(i).get("fechainicio");
            datos[12]=lista2.get(i).get("fechafinal");
            datos[13]=lista2.get(i).get("modalidad");
            model.addRow(datos);
            x++;
        }
        tbdatos.setModel(model);
    }
   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MatriculaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MatriculaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MatriculaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MatriculaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MatriculaForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnactualizar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnnuevo;
    private javax.swing.JComboBox<String> cboCarrera;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbdatos;
    private javax.swing.JTextField txtapellido;
    private javax.swing.JTextField txtciclo;
    private javax.swing.JTextField txtdistrito;
    private javax.swing.JTextField txtdni;
    private javax.swing.JTextField txtfechafin;
    private javax.swing.JTextField txtfechainicio;
    private javax.swing.JTextField txtidcarrera;
    private javax.swing.JTextField txtmodalidad;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtprecio;
    // End of variables declaration//GEN-END:variables
}
